<a href="https://colab.research.google.com/github/Lauraleejack/go-my-code/blob/main/grades_analysis_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#this is program for a grade analysis for students
import numpy as np

grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])
mean_grade = np.mean(grades)
median_grade = np.median(grades)
stan_grade = np.std(grades)

print("mean grade:", mean_grade)
print("median grade:", median_grade)
print("standard deviation:", stan_grade)

# Finding the max and min grades
max_gr = np.max(grades)
min_gr = np.min(grades)

sgrades = np.sort(grades)
print(sgrades)

high_grd=np.argmax(grades)
print(high_grd)

stud_90 = np.sum(grades > 90)
print(stud_90)

abv_90 = np.mean(grades > 90) * 100
print(abv_90)

perc_below75 = np.mean(grades < 75) * 100
print(perc_below75)

high_performers = grades[grades > 90]
print(high_performers)

passing_grades = grades[grades > 75]
print(passing_grades)

mean grade: 87.5
median grade: 88.5
standard deviation: 6.591661399070799
[75 80 83 85 88 89 90 92 95 98]
7
3
30.0
0.0
[92 95 98]
[85 90 88 92 95 80 98 89 83]
